version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: autocomplete
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      #- postgres-data:/var/lib/postgresql/data
      - ./backend/src:/usr/src/app/src # Hot-reload para desenvolvimento

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data: