version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules  # impede que node_modules do host sobrescreva os do container
    ports:
      - "4000:4000"
    command: npm run dev  # override opcional do CMD
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
