import { Trie } from './utils/trie';

const suggestionsData =  [
  "JavaScript frameworks",
  "Java programming",
  "JavaScript ES6",
  "Java Spring Boot",
  "JavaScript React",
  "Java collections",
  "JavaScript promises",
  "Java streams",
  "JavaScript async/await",
  "Java lambda expressions",
  "JavaScript modules",
  "Java design patterns",
  "JavaScript testing",
  "Java microservices",
  "JavaScript performance",
  "Java concurrency",
  "JavaScript security",
  "Java web development",
  "JavaScript build tools",
  "Java REST APIs",
  "Python programming",
  "Python Django",
  "Python Flask",
  "Python data science",
  "Python machine learning",
  "Python web scraping",
  "Python automation",
  "Python pandas",
  "Python numpy",
  "Python matplotlib",
  "React hooks",
  "React components",
  "React state management",
  "React router",
  "React testing",
  "React performance",
  "React native",
  "React context",
  "React redux",
  "React typescript",
  "React 1hooks",
  "React 1components",
  "React 1state management",
  "React 1router",
  "React 1testing",
  "React 1performance",
  "React 1native",
  "React 1context",
  "React 1redux",
  "React 1typescript",
  "Node.js development",
  "Node.js express",
  "Node.js API",
  "Node.js modules",
  "Node.js async",
  "Node.js streams",
  "Node.js testing",
  "Node.js deployment",
  "Node.js security",
  "Node.js performance",
  "HTML5 features",
  "HTML semantic",
  "HTML forms",
  "HTML accessibility",
  "HTML validation",
  "HTML canvas",
  "HTML audio",
  "HTML video",
  "HTML geolocation",
  "HTML storage",
  "CSS3 animations",
  "CSS flexbox",
  "CSS grid",
  "CSS responsive",
  "CSS preprocessors",
  "CSS frameworks",
  "CSS variables",
  "CSS transforms",
  "CSS transitions",
  "CSS media queries",
  "GraphQL queries",
  "GraphQL mutations",
  "GraphQL subscriptions",
  "GraphQL schema",
  "GraphQL resolvers",
  "GraphQL federation",
  "GraphQL caching",
  "GraphQL security",
  "GraphQL testing",
  "GraphQL performance",
  "Docker containers",
  "Docker compose",
  "Docker images",
  "Docker networking",
  "Docker volumes",
  "Docker security",
  "Docker deployment",
  "Docker orchestration",
  "Docker swarm",
  "Docker kubernetes",
  "Database design",
  "Database optimization",
  "Database migrations",
  "Database indexing",
  "Database transactions",
  "Database replication",
  "Database backup",
  "Database security",
  "Database performance",
  "Database normalization",
  "API development",
  "API design",
  "API testing",
  "API documentation",
  "API security",
  "API versioning",
  "API authentication",
  "API rate limiting",
  "API monitoring",
  "API gateway",
  "Web security",
  "Web performance",
  "Web accessibility",
  "Web standards",
  "Web optimization",
  "Web analytics",
  "Web deployment",
  "Web testing",
  "Web frameworks",
  "Web components"
];
  
const trie = new Trie();
for (const word of suggestionsData) {
  trie.insert(word);
}

export const resolvers = {
  Query: {
    suggestions: (_: any, { term }: { term: string }) => {
      if (term.length < 4) return [];

      const matches = trie.findPrefix(term, 20);

      return matches.map((text, index) => ({
        id: index.toString(),
        term: text
      }));
    }
  }
};